import { app, ipcMain, BrowserWindow } from 'electron';
import { createServer } from 'node:http';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import { previewWebsite } from '../desktop/preview.ts';
import { AgentBrowser } from '../desktop/browser.ts';
void app.whenReady().then(async()=>{
const dir=await mkdtemp(join(tmpdir(),'pa-browser-'));
const server=createServer((_req,res)=>{res.setHeader('Content-Type','text/html');res.end('<html><body><input placeholder="Name"><button onclick="document.querySelector(\'p\').textContent=document.querySelector(\'input\').value">Save</button><p>Empty</p></body></html>');});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
let resumed=false;
let browser=new AgentBrowser(dir,resolve('.'),()=>({folder:dir}),()=>{},()=>{resumed=true;});
try {
 await browser.start();const host=new BrowserWindow({width:1160,height:800,show:true});browser.attach(host);
 assert.equal(browser.show().empty,true);
 const url=`http://127.0.0.1:${(server.address() as any).port}`;
 const call=(workerId:string,input:any)=>{console.log('Checking '+input.action);return browser.command({projectId:'qa',workerId,...input});};
 const a=await call('a',{action:'open',url,label:'Data entry'}),b=await call('b',{action:'open',url,label:'Verification'});
 const failed=await call('a',{action:'open',url:'http://127.0.0.1:1',label:'Recovery'});
 assert.ok(failed.error);
 await call('a',{action:'navigate',id:failed.id,url});
 assert.ok((await call('a',{action:'screenshot',id:failed.id})).image.length>100,'Recovered navigation must support screenshots');
 assert.notEqual(a.id,b.id);
 await call('a',{action:'fill',id:a.id,selector:'input',text:'Collaboration'});
 await call('a',{action:'click',id:a.id,selector:'button'});
 assert.match((await call('a',{action:'observe',id:a.id})).text,/Collaboration/);
 assert.match((await call('b',{action:'observe',id:b.id})).text,/Empty/);
 await assert.rejects(call('b',{action:'click',id:a.id,selector:'button'}),/owning worker/);
 await call('a',{action:'handoff',id:a.id,to:'b'});
 assert.match((await call('b',{action:'observe',id:a.id})).text,/Collaboration/);
 const shot=await call('b',{action:'screenshot',id:a.id});assert.ok(shot.image.length>100);
 const otherShot=await call('b',{action:'screenshot',id:b.id});assert.ok(otherShot.image.length>100);
 const state=browser.state();assert.equal(state.instances.length,3);
 await call('b',{action:'needs_input',id:a.id,text:'Please sign in'});
 assert.equal((await call('b',{action:'click',id:a.id,selector:'button'})).waiting,true);
 assert.match((await call('b',{action:'observe',id:b.id})).text,/Empty/);
 const instances=(browser as any).instances;
 assert.equal(instances.get(a.id).view.webContents.session,instances.get(b.id).view.webContents.session);
 assert.equal(await instances.get(b.id).view.webContents.executeJavaScript('typeof require'),'undefined');
 await browser.continueSelected();assert.equal(resumed,true);assert.equal(browser.state().expanded,false);
 await writeFile(join(dir,'index.html'),'<html><button id="keep" onclick="localStorage.setItem(\'pa-proof\',\'Remembered across restart\')">Keep</button><p id="stored"></p><script src="app.js"></script></html>');await writeFile(join(dir,'app.js'),'document.title="Relative assets loaded";document.querySelector("#stored").textContent=localStorage.getItem("pa-proof")||""');
 const preview=await previewWebsite(join(dir,'index.html'));assert.equal(preview.webContents.getTitle(),'Relative assets loaded');preview.destroy();
 const local=await call('a',{action:'open',url:join(dir,'index.html')});assert.equal(local.title,'Relative assets loaded');
 const count=browser.state().instances.length;
 await assert.rejects(call('a',{action:'open',url:join(dir,'missing-folder/index.html')}));
 assert.equal(browser.state().instances.length,count,'An invalid path must not leave an empty selected browser');
 const fileURL=await call('a',{action:'open',url:pathToFileURL(join(dir,'index.html')).href});
 assert.equal(fileURL.title,'Relative assets loaded');assert.equal(browser.state().selected,fileURL.id);
 await call('a',{action:'navigate',id:fileURL.id,url:fileURL.url});
 assert.equal((await call('a',{action:'navigate',id:fileURL.id,url:fileURL.url})).title,'Relative assets loaded','Reload must keep the local server alive');
 await call('a',{action:'click',id:fileURL.id,selector:'#keep'});
 for(const item of (await call('a',{action:'list'})).instances)await call(item.workerId,{action:'finish',id:item.id});
 const total=browser.state().instances.length;
 await browser.close();ipcMain.removeHandler('browser-ui');
 browser=new AgentBrowser(dir,resolve('.'),()=>({folder:dir}),()=>{},()=>{throw Error('Finished browser unexpectedly resumed its worker');});
 await browser.start();browser.attach(host);await browser.restore();
 assert.equal(browser.state().instances.length,total);
 const restored=await call('a',{action:'observe',id:fileURL.id});
 assert.equal(restored.url,fileURL.url,'Local preview origin changed on restart');
 assert.match(restored.text,/Remembered across restart/);
 await browser.removeProject('qa');assert.equal(browser.state().instances.length,0);
 console.log('Browser instances, interaction, handoff, screenshot, shared sessions, and isolation passed.');
} finally {await browser.close();ipcMain.removeHandler('browser-ui');server.close();await rm(dir,{recursive:true,force:true});app.quit();}

}).catch(error=>{console.error(error);app.exit(1);});
